// YAMNet AudioSet class names — 521 classes in model output order.
// Source: https://github.com/tensorflow/models/tree/master/research/audioset/yamnet
// Used to map YAMNet output indices to human-readable labels.

export const YAMNET_CLASSES: string[] = [
  "Speech", "Male speech", "Female speech", "Child speech", "Conversation",
  "Narration", "Babbling", "Speech synthesizer", "Shout", "Bellow",
  "Whoop", "Yell", "Children shouting", "Screaming", "Whispering",
  "Laughter", "Baby laughter", "Giggling", "Snicker", "Belly laugh",
  "Chuckle", "Crying", "Baby cry", "Whimper", "Wail",
  "Sigh", "Singing", "Choir", "Yodeling", "Chant",
  "Mantra", "Male singing", "Female singing", "Child singing", "Synthetic singing",
  "Rapping", "Humming", "Groan", "Grunt", "Whistling",
  "Breathing", "Wheeze", "Snoring", "Gasp", "Pant",
  "Snort", "Cough", "Throat clearing", "Sneeze", "Sniff",
  "Run", "Shuffle", "Walk / footsteps", "Chewing", "Biting",
  "Gargling", "Surface contact", "Hands", "Finger snapping", "Clapping",
  "Heart sounds", "Burping", "Stomach rumble", "Hiccup", "Fart",
  "Slap", "Smack", "Knock", "Tap", "Squeak",
  "Bang", "Thud", "Thump", "Crash", "Breaking",
  "Bouncing", "Whack", "Splat", "Scrape", "Rub",
  "Roll", "Crushing", "Humming (mechanism)", "Hiss", "Buzz",
  "Rustle", "Crackle", "Crunch", "Squish", "Boing",
  "Silence", "Music", "Musical instrument", "Plucked string", "Guitar",
  "Electric guitar", "Bass guitar", "Acoustic guitar", "Steel guitar", "Banjo",
  "Sitar", "Ukulele", "Mandolin", "Zither", "Keyboard (instrument)",
  "Piano", "Electric piano", "Organ", "Electronic organ", "Hammond organ",
  "Synthesizer", "Sampler", "Harpsichord", "Percussion", "Drum kit",
  "Drum machine", "Drum", "Snare drum", "Rimshot", "Drum roll",
  "Bass drum", "Timpani", "Tabla", "Cymbal", "Hi-hat",
  "Wood block", "Tambourine", "Rattle", "Maracas", "Gong",
  "Tubular bells", "Mallet percussion", "Marimba", "Glockenspiel", "Vibraphone",
  "Xylophone", "Tinkle bell", "Cowbell", "Triangle", "Tuning fork",
  "Chime", "Bell", "Jingle bell", "Wind instrument", "Flute",
  "Piccolo", "Oboe", "Clarinet", "Saxophone", "Trumpet",
  "Trombone", "Tuba", "French horn", "Cornet", "Bugle",
  "Brass instrument", "Bowed string", "String section", "Violin", "Viola",
  "Cello", "Double bass", "Bow", "Pluck", "Music of Africa",
  "Music of Latin America", "Music of Bollywood", "Beatboxing", "Gospel music",
  "Pop music", "Hip hop music", "Rhythm and blues", "Rock music", "Indie rock",
  "Metal", "Punk rock", "Grunge", "Progressive rock", "Rock and roll",
  "Psychedelic rock", "Classical music", "Opera", "Electronic music", "House music",
  "Techno", "Dubstep", "Drum and bass", "Electronica", "Electronic dance music",
  "Ambient music", "New-age music", "Vocal music", "A cappella", "Soul music",
  "Funk", "Reggae", "Country", "Swing music", "Bluegrass",
  "Flamenco", "Folk music", "Middle Eastern music", "Ska", "Traditional music",
  "Independent music", "Song", "Background music", "Theme music", "Jingle",
  "Soundtrack", "Lullaby", "Video game music", "Christmas music", "Dance music",
  "Wedding music", "Happy music", "Sad music", "Tender music", "Exciting music",
  "Angry music", "Scary music", "Wind", "Rustling leaves", "Wind noise",
  "Thunderstorm", "Thunder", "Rain", "Raindrop", "Rain on surface",
  "Stream", "Waterfall", "Ocean", "Water", "Splashing water",
  "Gurgling water", "Fire", "Crackle (fire)", "Static noise", "Noise",
  "White noise", "Pink noise", "Throbbing", "Reverberation", "Echo",
  "Ambience", "Hum", "Animal", "Domestic animal", "Dog",
  "Dog bark", "Bow-wow", "Growling (dog)", "Whimper (dog)", "Cat",
  "Purring", "Meow", "Hiss (cat)", "Caterwaul", "Livestock",
  "Horse", "Clip-clop", "Neigh", "Rooster", "Pig",
  "Cow", "Goat", "Sheep", "Fowl", "Duck",
  "Bird", "Bird vocalization", "Bird call", "Chirp", "Caw",
  "Crow", "Owl", "Pigeon", "Frog", "Cricket",
  "Insect", "Bee", "Fly", "Mosquito", "Rodent",
  "Mouse", "Patter", "Snake", "Wildlife", "Jungle",
  "Mechanisms", "Machine", "Mechanical fan", "Air conditioning", "HVAC",
  "Printer", "Camera", "Single-lens reflex camera", "Shutter", "Copier",
  "Typewriter", "Computer keyboard", "Mouse click", "Writing", "Alarm",
  "Telephone bell", "Ringtone", "Telephone dialing", "Busy signal", "Alarm clock",
  "Siren", "Civil defense siren", "Buzzer", "Smoke detector", "Fire alarm",
  "Foghorn", "Whistle", "Steam whistle", "Mechanisms (other)", "Clock",
  "Tick-tock", "Tick", "Metronome", "Ratchet", "Sonar",
  "Ping", "Ding", "Tools", "Power tool", "Drill",
  "Circular saw", "Chain saw", "Jigsaw", "Nail gun", "Hammer",
  "Jackhammer", "Excavator", "Lawn mower", "Leaf blower", "Blender",
  "Vaccum cleaner", "Dishwasher", "Washing machine", "Tumble dryer", "Microwave oven",
  "Zipper", "Velcro", "Scissors", "Electric shaver", "Hair dryer",
  "Door", "Doorbell", "Ding-dong", "Sliding door", "Slam",
  "Latch", "Squeak (door)", "Keys", "Drawer", "Cupboard",
  "Dishes / pots / pans", "Cutlery", "Frying pan", "Pour", "Fill",
  "Water tap / faucet", "Toilet flush", "Toothbrush", "Bath", "Shower",
  "Crowd", "Hubbub", "Children playing", "Cheering", "Applause",
  "Booing", "Wail (crowd)", "Chatter", "Babble (crowd)", "White noise (social)",
  "Vehicle", "Car", "Vehicle horn", "Beep", "Car alarm",
  "Power window", "Skidding", "Tire squeal", "Crash (vehicle)", "Truck",
  "Air brakes", "Air horn", "Reversing beeps", "Bus", "Emergency vehicle",
  "Police siren", "Ambulance siren", "Fire engine siren", "Bicycle bell",
  "Skateboard", "Engine", "Engine starting", "Idling engine", "Accelerating engine",
  "Diesel engine", "Motorcycle", "Bicycle", "Train", "Train whistle",
  "Train horn", "Railroad car", "Train wheels", "Subway / underground",
  "Aircraft", "Aircraft engine", "Jet engine", "Propeller aircraft", "Helicopter",
  "Fixed-wing aircraft", "Boat", "Ship", "Sailboat", "Motorboat",
  "Foghorn (marine)", "Rowboat", "Canoe", "Kayak", "Gunshot / gunfire",
  "Machine gun", "Fusillade", "Artillery fire", "Rocket", "Explosion",
  "Boom", "Fireworks", "Cap gun", "Firecracker",
];
